// lib/projects.ts
// ─────────────────────────────────────────────────────────────
// Task & Project Management Engine — the operational PM layer.
//
//   • work_projects ...... Jira/Monday-style boards (manager- or IC-created).
//   • verified_tasks ..... the VERIFIED (blue) task layer — every row here is
//                          human-authored OR human-approved.
//   • ai_inference_tasks . model-suggested sub-tasks (amber). Generated by the
//                          server route (lib/ai/subtasks.ts); read here so the
//                          UI can show them for review. APPROVING one promotes
//                          it into verified_tasks — the only path AI work
//                          becomes a fact. (See approveInferenceTask.)
//
// All reads/writes go through the browser client + RLS (lib/supabase.ts).
// AI rows are NEVER inserted from the client — only the server route writes
// to ai_inference_tasks. Here we only READ them and flip them on approval.
// ─────────────────────────────────────────────────────────────
import { supabase } from "@/lib/supabase";
import { writeAuditLog } from "@/lib/audit";

export type ProjectStatus = "active" | "archived" | "completed";
export type TaskBoardStatus = "todo" | "in_progress" | "blocked" | "done";
export type TaskPriority = "low" | "medium" | "high" | "urgent";
export type TaskOrigin = "human" | "ai_approved";

export type WorkProject = {
  id: string;
  org_id: string;
  name: string;
  description: string | null;
  owner_id: string;
  team_lead_id: string | null;
  status: ProjectStatus;
  color: string | null;
  start_date: string | null;
  target_date: string | null;
  created_at: string;
  updated_at: string;
};

export type VerifiedTask = {
  id: string;
  org_id: string;
  project_id: string | null;
  parent_task_id: string | null;
  title: string;
  detail: string | null;
  assignee_id: string | null;
  created_by: string | null;
  status: TaskBoardStatus;
  priority: TaskPriority;
  due_date: string | null;
  origin: TaskOrigin;
  source_inference_id: string | null;
  achievement_id: string | null;
  completed_at: string | null;
  frozen_at: string | null;
  created_at: string;
  updated_at: string;
};

/** A model-suggested sub-task (amber). Server-written; client only reads + reviews. */
export type InferenceTask = {
  id: string;
  org_id: string;
  project_id: string | null;
  parent_task_id: string;
  suggested_for: string | null;
  title: string;
  detail: string | null;
  rationale: string | null;
  sequence: number;
  confidence: number | null;
  model: string | null;
  status: "pending" | "approved" | "rejected";
  reviewed_by: string | null;
  reviewed_at: string | null;
  approved_task_id: string | null;
  generated_by: string | null;
  created_at: string;
};

export const BOARD_COLUMNS: { key: TaskBoardStatus; label: string }[] = [
  { key: "todo", label: "To do" },
  { key: "in_progress", label: "In progress" },
  { key: "blocked", label: "Blocked" },
  { key: "done", label: "Done" },
];

const PROJECT_SELECT =
  "id, org_id, name, description, owner_id, team_lead_id, status, color, start_date, target_date, created_at, updated_at";
const TASK_SELECT =
  "id, org_id, project_id, parent_task_id, title, detail, assignee_id, created_by, status, priority, due_date, origin, source_inference_id, achievement_id, completed_at, frozen_at, created_at, updated_at";
const INFERENCE_SELECT =
  "id, org_id, project_id, parent_task_id, suggested_for, title, detail, rationale, sequence, confidence, model, status, reviewed_by, reviewed_at, approved_task_id, generated_by, created_at";

// ── Projects ──────────────────────────────────────────────────────
export async function fetchProjects(): Promise<WorkProject[]> {
  const { data, error } = await supabase
    .from("work_projects")
    .select(PROJECT_SELECT)
    .neq("status", "archived")
    .order("created_at", { ascending: false });
  if (error) throw error;
  return (data ?? []) as WorkProject[];
}

export async function createProject(
  actorId: string,
  orgId: string,
  input: {
    name: string;
    description?: string;
    teamLeadId?: string | null;
    color?: string;
    startDate?: string | null;
    targetDate?: string | null;
  },
): Promise<WorkProject> {
  const { data, error } = await supabase
    .from("work_projects")
    .insert({
      org_id: orgId,
      name: input.name.trim(),
      description: input.description?.trim() || null,
      owner_id: actorId,
      team_lead_id: input.teamLeadId ?? null,
      color: input.color ?? null,
      start_date: input.startDate || null,
      target_date: input.targetDate || null,
    })
    .select(PROJECT_SELECT)
    .single();
  if (error) throw error;

  await writeAuditLog({
    actorId,
    action: "project_created",
    targetTable: "work_projects",
    targetId: data.id,
    changes: { name: data.name, team_lead_id: data.team_lead_id },
  });
  return data as WorkProject;
}

// ── Verified tasks (the blue layer) ───────────────────────────────
export async function fetchTasks(opts: { projectId?: string; assigneeId?: string }): Promise<VerifiedTask[]> {
  let q = supabase.from("verified_tasks").select(TASK_SELECT);
  if (opts.projectId) q = q.eq("project_id", opts.projectId);
  if (opts.assigneeId) q = q.eq("assignee_id", opts.assigneeId);
  const { data, error } = await q.order("created_at", { ascending: true });
  if (error) throw error;
  return (data ?? []) as VerifiedTask[];
}

/** A manager's view of their reports' tasks (RLS "vt: manager manage" allows the read). */
export async function fetchTeamTasks(reportIds: string[]): Promise<VerifiedTask[]> {
  if (!reportIds.length) return [];
  const { data, error } = await supabase
    .from("verified_tasks")
    .select(TASK_SELECT)
    .in("assignee_id", reportIds)
    .order("created_at", { ascending: true });
  if (error) throw error;
  return (data ?? []) as VerifiedTask[];
}

export async function createTask(
  actorId: string,
  orgId: string,
  input: {
    title: string;
    detail?: string;
    projectId?: string | null;
    parentTaskId?: string | null;
    assigneeId?: string | null;
    priority?: TaskPriority;
    dueDate?: string | null;
  },
): Promise<VerifiedTask> {
  const { data, error } = await supabase
    .from("verified_tasks")
    .insert({
      org_id: orgId,
      project_id: input.projectId ?? null,
      parent_task_id: input.parentTaskId ?? null,
      title: input.title.trim(),
      detail: input.detail?.trim() || null,
      assignee_id: input.assigneeId ?? actorId,
      created_by: actorId,
      priority: input.priority ?? "medium",
      due_date: input.dueDate ?? null,
      origin: "human",
    })
    .select(TASK_SELECT)
    .single();
  if (error) throw error;

  await writeAuditLog({
    actorId,
    action: "task_created",
    targetTable: "verified_tasks",
    targetId: data.id,
    changes: { title: data.title, project_id: data.project_id, assignee_id: data.assignee_id },
  });
  return data as VerifiedTask;
}

export async function updateTaskBoardStatus(
  actorId: string,
  taskId: string,
  status: TaskBoardStatus,
): Promise<VerifiedTask> {
  const { data, error } = await supabase
    .from("verified_tasks")
    .update({
      status,
      completed_at: status === "done" ? new Date().toISOString() : null,
      updated_at: new Date().toISOString(),
    })
    .eq("id", taskId)
    .select(TASK_SELECT)
    .single();
  if (error) throw error;

  await writeAuditLog({
    actorId,
    action: "task_status_changed",
    targetTable: "verified_tasks",
    targetId: taskId,
    changes: { status },
  });
  return data as VerifiedTask;
}

// ── AI inference sub-tasks (amber) — read + review ────────────────
/** Pending model-suggested sub-tasks for a verified task (awaiting human review). */
export async function fetchInferenceSubtasks(parentTaskId: string): Promise<InferenceTask[]> {
  const { data, error } = await supabase
    .from("ai_inference_tasks")
    .select(INFERENCE_SELECT)
    .eq("parent_task_id", parentTaskId)
    .order("sequence", { ascending: true });
  if (error) throw error;
  return (data ?? []) as InferenceTask[];
}

/**
 * BRIDGE — a human approves an AI-suggested sub-task. This is the ONLY way an
 * AI inference becomes a verified fact: we insert a real verified_task (origin
 * 'ai_approved', linked back) and flip the inference row to 'approved'. Mirrors
 * the achievements bridge in lib/tasks.ts. RLS lets the subject or their
 * manager perform both writes.
 */
export async function approveInferenceTask(actorId: string, inf: InferenceTask): Promise<VerifiedTask> {
  if (inf.status !== "pending") throw new Error("This suggestion has already been reviewed.");

  const { data: task, error: taskErr } = await supabase
    .from("verified_tasks")
    .insert({
      org_id: inf.org_id,
      project_id: inf.project_id,
      parent_task_id: inf.parent_task_id,
      title: inf.title,
      detail: inf.detail,
      assignee_id: inf.suggested_for ?? actorId,
      created_by: actorId,
      origin: "ai_approved",
      source_inference_id: inf.id,
    })
    .select(TASK_SELECT)
    .single();
  if (taskErr) throw taskErr;

  const { error: flipErr } = await supabase
    .from("ai_inference_tasks")
    .update({
      status: "approved",
      reviewed_by: actorId,
      reviewed_at: new Date().toISOString(),
      approved_task_id: task.id,
    })
    .eq("id", inf.id);
  if (flipErr) throw flipErr;

  await writeAuditLog({
    actorId,
    action: "ai_subtask_approved",
    targetTable: "ai_inference_tasks",
    targetId: inf.id,
    changes: { promoted_to: task.id, parent_task_id: inf.parent_task_id },
  });
  return task as VerifiedTask;
}

/**
 * BRIDGE to the 5-level verification chain — a manager promotes a COMPLETED
 * verified_task into an L2 Manager-Verified achievement for the assignee, and
 * links it back. Relies on the "ach: manager insert from task" RLS policy
 * (manager-of, own org, L2, not pending_executive). Mirrors lib/tasks.ts.
 * No-op if the task isn't done or was already promoted.
 */
export async function promoteTaskToVerifiedAchievement(
  managerId: string,
  task: VerifiedTask,
): Promise<string> {
  if (task.status !== "done") throw new Error("Only completed tasks can be verified as achievements.");
  if (task.achievement_id) return task.achievement_id;
  if (!task.assignee_id) throw new Error("This task has no assignee to credit.");

  const description = task.detail ? `${task.title}: ${task.detail}` : task.title;

  const { data: ach, error: achErr } = await supabase
    .from("achievements")
    .insert({
      profile_id: task.assignee_id,
      org_id: task.org_id,
      kind: "achievement",
      description,
      achievement_date: (task.completed_at ?? task.created_at).slice(0, 10),
      verification_level: 2, // Manager Verified
      pending_executive: false,
    })
    .select("id")
    .single();
  if (achErr) throw achErr;

  const { data: linked, error: linkErr } = await supabase
    .from("verified_tasks")
    .update({ achievement_id: ach.id, updated_at: new Date().toISOString() })
    .eq("id", task.id)
    .select(TASK_SELECT)
    .single();
  if (linkErr) throw linkErr;

  await writeAuditLog({
    actorId: managerId,
    action: "task_promoted_to_achievement",
    targetTable: "verified_tasks",
    targetId: task.id,
    changes: { achievement_id: ach.id, profile_id: task.assignee_id, verification_level: 2 },
  });

  void linked;
  return ach.id as string;
}

/** Reject a suggestion — it stays in the amber table, never crosses to verified. */
export async function rejectInferenceTask(actorId: string, inferenceId: string): Promise<void> {
  const { error } = await supabase
    .from("ai_inference_tasks")
    .update({ status: "rejected", reviewed_by: actorId, reviewed_at: new Date().toISOString() })
    .eq("id", inferenceId);
  if (error) throw error;

  await writeAuditLog({
    actorId,
    action: "ai_subtask_rejected",
    targetTable: "ai_inference_tasks",
    targetId: inferenceId,
  });
}
